version: "3.9"

services:
  headcoach:
    container_name: headcoach
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=4545
      - LOG_LEVEL=debug
    volumes:
      - ./src:/app/src
    ports:
      - 4545:4545
    external_links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:14.4-alpine
    container_name: headcoach-pgsql
    environment:
      - POSTGRES_DB=motivator
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
