name: Build and push image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --tag "ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}"
        
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      
      - name: Push image
        run: |
          docker push ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA